# Generated by Django 3.2.5 on 2021-09-11 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cidadesatendimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cidadesatendimento',
            old_name='codigo_bge',
            new_name='codigo_ibge',
        ),
    ]
