# Generated by Django 3.2.5 on 2021-09-11 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_codigo_bge_cidadesatendimento_codigo_ibge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nome_completo',
            new_name='name_completo',
        ),
    ]
